=== arnoldasstrukcinskas/Antras_PD_PI24SN/Antras_PD_PI24SN_provider/src/main/resources/data/drones.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="drones">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="drone" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="droneName"/>
              <xs:element type="xs:short" name="batteryCapacity"/>
              <xs:element type="xs:double" name ="price"/>
              <xs:element type="xs:string" name="droneNew"/>
              <xs:element type="xs:string" name="framsShape"/>
              <xs:element type="xs:string" name="isAutonomus"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== arnoldasstrukcinskas/Antras_PD_PI24SN/Antras_PD_PI24SN_provider/src/main/resources/Backup/drones.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<drones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="drones.xsd">
    <drone>
        <droneName>AeroFalcon-X1</droneName>
        <batteryCapacity>5200</batteryCapacity>
        <price>1475.2</price>
        <droneNew>true</droneNew>
        <framsShape>X</framsShape>
        <isAutonomus>true</isAutonomus>
    </drone>
    <drone>
        <droneName>SkyRanger-A3</droneName>
        <batteryCapacity>6100</batteryCapacity>
        <price>1320.5</price>
        <droneNew>true</droneNew>
        <framsShape>O</framsShape>
        <isAutonomus>true</isAutonomus>
    </drone>
    <drone>
        <droneName>StormWing-B3</droneName>
        <batteryCapacity>5800</batteryCapacity>
        <price>1589.99</price>
        <droneNew>true</droneNew>
        <framsShape>H</framsShape>
        <isAutonomus>true</isAutonomus>
    </drone>
    <drone>
        <droneName>IronFalcon-C4</droneName>
        <batteryCapacity>7000</batteryCapacity>
        <price>2199.0</price>
        <droneNew>false</droneNew>
        <framsShape>H</framsShape>
        <isAutonomus>false</isAutonomus>
    </drone>
    <drone>
        <droneName>NightHawk-D5</droneName>
        <batteryCapacity>6400</batteryCapacity>
        <price>1749.95</price>
        <droneNew>true</droneNew>
        <framsShape>X</framsShape>
        <isAutonomus>true</isAutonomus>
    </drone>
    <drone>
        <droneName>SkyHunter-E6</droneName>
        <batteryCapacity>5900</batteryCapacity>
        <price>1399.75</price>
        <droneNew>true</droneNew>
        <framsShape>X</framsShape>
        <isAutonomus>false</isAutonomus>
    </drone>
    <drone>
        <droneName>AtlasWing-F7</droneName>
        <batteryCapacity>7200</batteryCapacity>
        <price>2450.0</price>
        <droneNew>true</droneNew>
        <framsShape>O</framsShape>
        <isAutonomus>true</isAutonomus>
    </drone>
    <drone>
        <droneName>PhantomScout-G8</droneName>
        <batteryCapacity>5600</batteryCapacity>
        <price>1250.3</price>
        <droneNew>true</droneNew>
        <framsShape>L</framsShape>
        <isAutonomus>false</isAutonomus>
    </drone>
    <drone>
        <droneName>ThunderEye-H9</droneName>
        <batteryCapacity>6800</batteryCapacity>
        <price>1899.49</price>
        <droneNew>true</droneNew>
        <framsShape>X</framsShape>
        <isAutonomus>true</isAutonomus>
    </drone>
    <drone>
        <droneName>VectorFalcon-I10</droneName>
        <batteryCapacity>6100</batteryCapacity>
        <price>1675.0</price>
        <droneNew>false</droneNew>
        <framsShape>H</framsShape>
        <isAutonomus>false</isAutonomus>
    </drone>
    <drone>
        <droneName>SkyNomad-11</droneName>
        <batteryCapacity>6000</batteryCapacity>
        <price>1510.6</price>
        <droneNew>true</droneNew>
        <framsShape>X</framsShape>
        <isAutonomus>true</isAutonomus>
    </drone>
    <drone>
        <droneName>IronScout-12</droneName>
        <batteryCapacity>6300</batteryCapacity>
        <price>1620.85</price>
        <droneNew>true</droneNew>
        <framsShape>O</framsShape>
        <isAutonomus>false</isAutonomus>
    </drone>
    <drone>
        <droneName>NovaWing-13</droneName>
        <batteryCapacity>5700</batteryCapacity>
        <price>1349.99</price>
        <droneNew>true</droneNew>
        <framsShape>H</framsShape>
        <isAutonomus>true</isAutonomus>
    </drone>
    <drone>
        <droneName>HyperFalcon-98</droneName>
        <batteryCapacity>6900</batteryCapacity>
        <price>2099.0</price>
        <droneNew>true</droneNew>
        <framsShape>X</framsShape>
        <isAutonomus>true</isAutonomus>
    </drone>
    <drone>
        <droneName>QuantumEye-99</droneName>
        <batteryCapacity>7100</batteryCapacity>
        <price>2375.5</price>
        <droneNew>false</droneNew>
        <framsShape>X</framsShape>
        <isAutonomus>false</isAutonomus>
    </drone>
    <drone>
        <droneName>SkyTitan-100</droneName>
        <batteryCapacity>7500</batteryCapacity>
        <price>2799.99</price>
        <droneNew>true</droneNew>
        <framsShape>L</framsShape>
        <isAutonomus>true</isAutonomus>
    </drone>
</drones>
