=== arnoldasstrukcinskas/Antras_PD_PI24SN/Antras_PD_PI24SN_provider/src/main/resources/data/managers.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="managers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="manager" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:int" name="id"/>
                            <xs:element type="xs:integer" name="accountNumber"/>
                            <xs:element type="xs:string" name="username"/>
                            <xs:element type="xs:string" name="password"/>
                            <xs:element name="soldDrones">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="drone" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="droneName"/>
                                                    <xs:element type="xs:short" name="batteryCapacity"/>
                                                    <xs:element type="xs:double" name="price"/>
                                                    <xs:element type="xs:string" name="droneNew"/>
                                                    <xs:element type="xs:string" name="framsShape"/>
                                                    <xs:element type="xs:string" name="isAutonomus"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== arnoldasstrukcinskas/Antras_PD_PI24SN/Antras_PD_PI24SN_provider/managers.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<managers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="managers.xsd">
    <manager>
        <id>1</id>
        <accountNumber>13045653724082753497</accountNumber>
        <username>admin</username>
        <password></password>
        <soldDrones>
            <drone>
                <droneName>AeroFalcon-X1</droneName>
                <batteryCapacity>5200</batteryCapacity>
                <price>1475.2</price>
                <droneNew>true</droneNew>
                <framsShape>X</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
            <drone>
                <droneName>SkyNomad-11</droneName>
                <batteryCapacity>6000</batteryCapacity>
                <price>1510.6</price>
                <droneNew>true</droneNew>
                <framsShape>X</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
        </soldDrones>
    </manager>
    <manager>
        <id>1</id>
        <accountNumber>17478388203806195170</accountNumber>
        <username>user</username>
        <password></password>
        <soldDrones>
            <drone>
                <droneName>NovaWing-13</droneName>
                <batteryCapacity>5700</batteryCapacity>
                <price>1349.99</price>
                <droneNew>true</droneNew>
                <framsShape>H</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
            <drone>
                <droneName>HyperFalcon-98</droneName>
                <batteryCapacity>6900</batteryCapacity>
                <price>2099.0</price>
                <droneNew>true</droneNew>
                <framsShape>X</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
            <drone>
                <droneName>QuantumEye-99</droneName>
                <batteryCapacity>7100</batteryCapacity>
                <price>2375.5</price>
                <droneNew>false</droneNew>
                <framsShape>X</framsShape>
                <isAutonomus>false</isAutonomus>
            </drone>
        </soldDrones>
    </manager>
    <manager>
        <id>3</id>
        <accountNumber>8290013299286208802</accountNumber>
        <username>manager</username>
        <password></password>
        <soldDrones>
            <drone>
                <droneName>QuantumEye-99</droneName>
                <batteryCapacity>7100</batteryCapacity>
                <price>2375.5</price>
                <droneNew>false</droneNew>
                <framsShape>X</framsShape>
                <isAutonomus>false</isAutonomus>
            </drone>
            <drone>
                <droneName>AeroFalcon-X1</droneName>
                <batteryCapacity>5200</batteryCapacity>
                <price>1475.2</price>
                <droneNew>true</droneNew>
                <framsShape>X</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
            <drone>
                <droneName>AeroFalcon-X1</droneName>
                <batteryCapacity>5200</batteryCapacity>
                <price>1475.2</price>
                <droneNew>true</droneNew>
                <framsShape>X</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
            <drone>
                <droneName>StormWing-B3</droneName>
                <batteryCapacity>5800</batteryCapacity>
                <price>1589.99</price>
                <droneNew>true</droneNew>
                <framsShape>H</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
            <drone>
                <droneName>PhantomScout-G8</droneName>
                <batteryCapacity>5600</batteryCapacity>
                <price>1250.3</price>
                <droneNew>true</droneNew>
                <framsShape>L</framsShape>
                <isAutonomus>false</isAutonomus>
            </drone>
            <drone>
                <droneName>ThunderEye-H9</droneName>
                <batteryCapacity>6800</batteryCapacity>
                <price>1899.49</price>
                <droneNew>true</droneNew>
                <framsShape>X</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
        </soldDrones>
    </manager>
</managers>

=== arnoldasstrukcinskas/Antras_PD_PI24SN/Antras_PD_PI24SN_provider/src/main/resources/Backup/managers.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="managers.xsl"?>
<managers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="managers.xsd">
    <manager>
        <id>1</id>
        <accountNumber>627630144951673105</accountNumber>
        <username>admin</username>
        <password>admin</password>
        <soldDrones>
            <drone>
                <droneName>AeroFalcon-X1</droneName>
                <batteryCapacity>5200</batteryCapacity>
                <price>1475.2</price>
                <droneNew>true</droneNew>
                <framsShape>X</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
            <drone>
                <droneName>SkyRanger-A3</droneName>
                <batteryCapacity>6100</batteryCapacity>
                <price>1320.5</price>
                <droneNew>true</droneNew>
                <framsShape>O</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
            <drone>
                <droneName>NightHawk-D5</droneName>
                <batteryCapacity>6400</batteryCapacity>
                <price>1749.95</price>
                <droneNew>true</droneNew>
                <framsShape>X</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
        </soldDrones>
    </manager>
    <manager>
        <id>2</id>
        <accountNumber>14337904413229547998</accountNumber>
        <username>manager</username>
        <password>manager</password>
        <soldDrones>
            <drone>
                <droneName>IronFalcon-C4</droneName>
                <batteryCapacity>7000</batteryCapacity>
                <price>2199.0</price>
                <droneNew>false</droneNew>
                <framsShape>H</framsShape>
                <isAutonomus>false</isAutonomus>
            </drone>
            <drone>
                <droneName>StormWing-B3</droneName>
                <batteryCapacity>5800</batteryCapacity>
                <price>1589.99</price>
                <droneNew>true</droneNew>
                <framsShape>H</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
        </soldDrones>
    </manager>
    <manager>
        <id>3</id>
        <accountNumber>7950445090528196086</accountNumber>
        <username>user</username>
        <password>user</password>
        <soldDrones>
            <drone>
                <droneName>SkyNomad-11</droneName>
                <batteryCapacity>6000</batteryCapacity>
                <price>1510.6</price>
                <droneNew>true</droneNew>
                <framsShape>X</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
        </soldDrones>
    </manager>
</managers>

=== arnoldasstrukcinskas/Antras_PD_PI24SN/Antras_PD_PI24SN_provider/src/main/resources/data/managers.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<managers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="managers.xsd">
    <manager>
        <id>1</id>
        <accountNumber>16927267412019239773</accountNumber>
        <username>admin</username>
        <password></password>
        <soldDrones>
            <drone>
                <droneName>AeroFalcon-X1</droneName>
                <batteryCapacity>5200</batteryCapacity>
                <price>1475.2</price>
                <droneNew>true</droneNew>
                <framsShape>X</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
            <drone>
                <droneName>StormWing-B3</droneName>
                <batteryCapacity>5800</batteryCapacity>
                <price>1589.99</price>
                <droneNew>true</droneNew>
                <framsShape>H</framsShape>
                <isAutonomus>true</isAutonomus>
            </drone>
        </soldDrones>
    </manager>
    <manager>
        <id>1</id>
        <accountNumber>9763655703101446663</accountNumber>
        <username>aa</username>
        <password></password>
        <soldDrones/>
    </manager>
</managers>
